name: Create srs

on:
  push:
    branches: [ "main", "srs" ]
    paths:
      - .github/workflows/create-srs.yml
      - Categories/**
      - Services/**
      - src/**
      - Sing-box-compile-srs/**

jobs:
  compile-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Compile ruleset srs
        run: |
          docker run --rm \
          -v ${{ github.workspace }}/Categories:/app/Categories \
          -v ${{ github.workspace }}/Services:/app/Services \
          -v ${{ github.workspace }}/SRS:/app/SRS \
          itdoginfo/compilesrs:0.1

      - name: Set release tag
        run: echo "TAG_NAME=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: "${{ github.workspace }}/SRS/*.srs"
          tag_name: ${{ env.TAG_NAME }}